# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180105_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModelExtension',
        ),
    ]
