# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_usermodelextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/images/default/default_profile_picture_all.jpg', upload_to='pic_folder/'),
        ),
    ]
