# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180105_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/profiles/images/default/default_profile_picture_all.jpg', upload_to='static/profiles/images/photo_hub'),
        ),
    ]
